-- Add new table named "stories"
CREATE TABLE "stories" (
  "id" NUMBER GENERATED BY DEFAULT AS IDENTITY,
  "title" VARCHAR2(255),
  "author_id" NUMBER,
  CONSTRAINT "SYS_C008430" PRIMARY KEY ("id")
);
-- Add new table named "users"
CREATE TABLE "users" (
  "id" NUMBER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR2(255),
  "emails" VARCHAR2(255),
  CONSTRAINT "SYS_C008432" PRIMARY KEY ("id")
);
