-- atlas:pos users[type=table] internal/testdata/models/user.go:3-7
-- atlas:pos stories[type=table] internal/testdata/models/story.go:3-8

CREATE TABLE "users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY, "name" VARCHAR2(255), "emails" VARCHAR2(255), PRIMARY KEY ("id"));
CREATE TABLE "stories" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY, "title" VARCHAR2(255), "author_id" INTEGER, PRIMARY KEY ("id"), FOREIGN KEY ("author_id") REFERENCES "users" ("id"));
