-- atlas:pos items[type=table] internal/testdata/m2m/models/item.go:3-7
-- atlas:pos orders[type=table] internal/testdata/m2m/models/order.go:3-7
-- atlas:pos order_to_items[type=table] internal/testdata/m2m/models/orderitem.go:3-8

CREATE TABLE "items" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY ("id"));
CREATE TABLE "orders" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY ("id"));
CREATE TABLE "order_to_items" ("order_id" INTEGER, "item_id" INTEGER, PRIMARY KEY ("order_id", "item_id"), FOREIGN KEY ("item_id") REFERENCES "items" ("id"), FOREIGN KEY ("order_id") REFERENCES "orders" ("id"));
