CREATE TABLE "items" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY ("id"));
CREATE TABLE "orders" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY ("id"));
CREATE TABLE "order_to_items" ("order_id" INTEGER, "item_id" INTEGER, PRIMARY KEY ("order_id", "item_id"), FOREIGN KEY ("item_id") REFERENCES "items" ("id")  , FOREIGN KEY ("order_id") REFERENCES "orders" ("id")  );
