name: Go Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version-file: 'go.mod'
      - name: Run Go linters
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          args: --verbose --timeout=5m
          skip-pkg-cache: true
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version-file: 'go.mod'
      - name: Run tests
        run: go test -race ./...
  integration-test:
    strategy:
      matrix:
        dialect: [mysql, postgres, sqlite, mssql]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: '1.23'
      - uses: ariga/setup-atlas@2f3c785c89a15e1c0d07bcae3900fb5feb969eea # v0.3
      - working-directory: internal/testdata
        run: |
          atlas migrate diff --env bun --var dialect=${{ matrix.dialect }}
        env:
          ATLAS_TOKEN: ${{ secrets.ATLAS_TOKEN }}
      - working-directory: internal/testdata/m2m
        run: |
          atlas migrate diff --env bun --var dialect=${{ matrix.dialect }}
        env:
          ATLAS_TOKEN: ${{ secrets.ATLAS_TOKEN }}
      - name: Verify migrations generated
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'atlas migrate diff --env bun' and commit the changes"
            echo "$status"
            git --no-pager diff
            exit 1
          fi